version: "3"
services:
  core_bridge:
    build:
      context: .
      dockerfile: CoreBridge/Dockerfile
    container_name: core_bridge
    environment:
      - ConnectionStrings__Redis=redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/app/bne-gfs-06ffad36d462.json
    ports:
      - 8888:80
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
networks:
  docker-net:
    external: true
