name: Container Build and Push

on:
  push:
    branches:
      - develop
      - feat/gha-image-build
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

#env:
#  AWS_ROLE_ARN: arn:aws:iam::224392488438:role/GitHubActionECRPower
#  ECR_REGISTRY: 224392488438.dkr.ecr.ap-northeast-1.amazonaws.com

jobs:
  build-push-corebridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      #- uses: aws-actions/configure-aws-credentials@v1-node16
      #  with:
      #    role-to-assume: ${{ inputs.aws_role_arn }}
      #    aws-region: ${{ inputs.aws_region }}
      #- uses: docker/login-action@v2
      #  with:
      #    registry: ${{ inputs.ecr_registry }}
      - uses: docker/build-push-action@v3
        with:
          context: '.'
          file: './CoreBridge/Dockerfile'
          push: true
          tags: |
            ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ github.sha }}
            ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

